version: "3.9"
services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile.development
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=development
      - DB_HOSTNAME=sql10.freemysqlhosting.net
      - DB_USERNAME=sql10497971
      - DB_PASSWORD=XtAZW2b2ht
      - DB_DATABASE=sql10497971
      - DB_DRIVER=mysqli
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
