version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker Build
          command: |
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
            docker build . --pull -t ${DOCKER_IMAGE}
            docker tag ${DOCKER_IMAGE} ${DOCKER_IMAGE}
            docker push ${DOCKER_IMAGE}
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            docker tag ${DOCKER_IMAGE} registry.heroku.com/tugas-kelompok-pemweb/web
            docker push registry.heroku.com/tugas-kelompok-pemweb/web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku labs:enable --app=tugas-kelompok-pemweb runtime-new-layer-extract
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku stack:set container --app tugas-kelompok-pemweb
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release web --app tugas-kelompok-pemweb
            docker --version

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: .
          filters:
            branches:
              only: main
  deploy:
    jobs:
      - deploy:
          context: .
          filters:
            branches:
              only: main
