version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push --app tugas-kelompok-pemweb web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku labs:enable --app=tugas-kelompok-pemweb runtime-new-layer-extract
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku stack:set container --app tugas-kelompok-pemweb
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release web --app tugas-kelompok-pemweb

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          context: .
          filters:
            branches:
              only: main
