version: 2
jobs:
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push registry.heroku.com/tugas-kelompok-pemweb/web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release web --app registry.heroku.com/tugas-kelompok-pemweb/web

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          context: .
          filters:
            branches:
              only: main
